sudo: required

language: ruby

services:
  - docker

before_install:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y install docker-ce
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  - docker login -u "$QUAY_USERNAME" -p "$QUAY_PASSWORD" quay.io
  - docker pull dsexton/rails-ci:onbuild

script:
  - bundle exec rake build
