#!/bin/bash

set -xeo pipefail

# Node
# https://hub.docker.com/_/node/
NODE_VERSION=${1:-9.2.0}
NPM_CONFIG_LOGLEVEL=${2:-error}

curl -SLO "https://nodejs.org/dist/v$NODE_VERSION/node-v$NODE_VERSION-linux-x64.tar.xz"
tar -xJf "node-v$NODE_VERSION-linux-x64.tar.xz" -C /usr/local --strip-components=1
rm "node-v$NODE_VERSION-linux-x64.tar.xz"

npm set progress=false
npm install -g --progress=false yarn
npm cache clean --force

YARN_VERSION=$(yarn --version)
