#!/bin/bash

set -xeo pipefail

# MySQL
# https://hub.docker.com/_/mysql/

key='A4A9406876FCBD3C456770C88C718D3B5072E1F5'
export GNUPGHOME="$(mktemp -d)"
gpg --keyserver ha.pool.sks-keyservers.net --recv-keys "$key"
gpg --export "$key" > /etc/apt/trusted.gpg.d/mysql.gpg
rm -r "$GNUPGHOME"
apt-key list > /dev/null

MYSQL_MAJOR=${1:-5.7}
MYSQL_VERSION=${2:-5.7.20-1debian8}

echo "deb http://repo.mysql.com/apt/debian/ jessie mysql-${MYSQL_MAJOR}" > /etc/apt/sources.list.d/mysql.list

apt-get update
apt-get install -y --no-install-recommends \
	mysql-client
	\
# https://lists.debian.org/debian-devel-announce/2016/09/msg00000.html
	$( \
# if we use just "apt-cache show" here, it returns zero because "Can't select versions from package 'libmysqlclient-dev' as it is purely virtual", hence the pipe to grep
		if apt-cache show 'default-libmysqlclient-dev' 2>/dev/null | grep -q '^Version:'; then \
			echo 'default-libmysqlclient-dev'; \
		else \
			echo 'libmysqlclient-dev'; \
		fi \
	) \

rm -rf /var/lib/apt/lists/*
