#!/bin/bash

set -xeo pipefail

# MySQL
# https://hub.docker.com/_/mysql/

key='A4A9406876FCBD3C456770C88C718D3B5072E1F5'
export GNUPGHOME="$(mktemp -d)"
gpg --keyserver ha.pool.sks-keyservers.net --recv-keys "$key"
gpg --export "$key" > /etc/apt/trusted.gpg.d/mysql.gpg
rm -r "$GNUPGHOME"
apt-key list > /dev/null

MYSQL_MAJOR=${1:-5.7}
MYSQL_VERSION=${2:-5.7.20-1debian8}

echo "deb http://repo.mysql.com/apt/debian/ jessie mysql-${MYSQL_MAJOR}" > /etc/apt/sources.list.d/mysql.list

if apt-cache show 'default-libmysqlclient-dev' 2>/dev/null | grep -q '^Version:'; then
  MYSQL_PACKAGE='default-libmysqlclient-dev'
else
  MYSQL_PACKAGE='libmysqlclient-dev'
fi

apt-get update
apt-get install -y --no-install-recommends mysql-client $MYSQL_PACKAGE

rm -rf /var/lib/apt/lists/*
